### ISSUE TITLE
Google Solution Challenge

### ISSUE THREAD

**Issue by PushkarAdhyapak** [avinash201199/Competitions-and-Programs-List#114]
The mission of the 2022 Solution Challenge is to solve for one or more of the [United Nations 17 Sustainable Development Goals](https://developers.google.com/community/gdsc-solution-challenge/UN-goals) using Google technology.

Impact (60 points)
Does the entry establish a clear problem or challenge drawn from one or more of the United Nations 17 Sustainable Development Goals (SDGs), and is it clearly explained which specific SDG targets the entry is solving for? (10 points)
How effectively does the solution address the challenge identified by the team? (20 points)
Is there evidence of a next step? Does the team display a plan for future extension if they were to continue? (10 points)
Is there evidence that the solution has been thoroughly tested with real users? (10 points)
Is there evidence that the solution was iterated upon based on user feedback? (10 points)

Technology (40 points)
Does the solution implement all the technical components needed to solve the challenge? (10 points)
Has the team clearly explained what Google technology they used, why, and included guidance on how to run their code? (10 points)
Does the video demonstration show the working solution and how a user will interact with the solution? Does the demonstration highlight how Google's technologies are implemented, and also mention the value the technology provides the users? (10 points)
Has the team made effective product and technical decisions for their solution? (10 points)

website link - https://developers.google.com/community/gdsc-solution-challenge

**Comment by avinash201199** [comment]
@PushkarAdhyapak 
Go ahead you can add this :)

**Comment by PushkarAdhyapak** [comment]
Thanks @avinash201199
