### ISSUE TITLE
Can anyone create a website for this ? comment down to assign the issue !

### ISSUE THREAD

**Issue by avinash201199** [avinash201199/Competitions-and-Programs-List#115]

**Comment by Daksh777** [comment]
Would you be interested in using a static site generator? I think that would be the best fit here.

**Comment by avinash201199** [comment]
Let's try that

**Comment by Daksh777** [comment]
Okay, I'll make a sample website with a static website generator and then you can tell me if it's okay.

**Comment by DevParapalli** [comment]
I could script this into a simple HTML + CSS Page.

https://github.com/trentm/python-markdown2 this should be fine for the parsing ?
https://sindresorhus.com/github-markdown-css/ for the CSS seems right ?

**Comment by avinash201199** [comment]
> Okay, I'll make a sample website with a static website generator and then you can tell me if it's okay.

okay

**Comment by Abhishek-thakur1** [comment]
Hey! Long time no update. Can I go ahead with React.js

**Comment by AbirSantra** [comment]
Hi, I can help with this!

**Comment by avinash201199** [comment]
> Hey! Long time no update. Can I go ahead with React.js

Go ahead

**Comment by avinash201199** [comment]
> Hi, I can help with this!

your most welcome
