### ISSUE TITLE
Add more opportunities

### ISSUE THREAD

**Issue by shlok2740** [avinash201199/Competitions-and-Programs-List#126]
For Computer Science:

ACM ICPC
Yandex.Algorithm
VK Cup
IEEE Xtreme

For Data Science and Artificial Intelligence:

World Computer Chess Championship
Angry Birds AI Competition
Battle of Bots

For Cybersecurity:

Global Cyberlympics
NYU Cybersecurity Awareness Week
National Collegiate Cyber Defence Competition
MITRE Cyber Academy Contests
Cyber Fed
DARPA Cyber Grand Challenge

For Robotics:

DARPA Grand Robotics Challenge
VEX Robotics
BEST Robotics
BotBall
GEAR Robotics Competition
Int’l Robot Olympiad

For Mathematics:

William Lowell Putnam Mathematics Competition
International Mathematics Competition for Undergraduates
Mathematical Contest in Modelling
Interdisciplinary Contest in Modelling
Math Jeopardy Contest
SIAM Student Paper Competition

For Physics:

Rudolf Ortvay Competition in Physics
University Physics Competition

Annual Hackathons and Tech Contests:

NASA Space Apps Challenge
Hack MIT
Make MIT
Penapps
MIT Hacking Medicine
University Hacker Olympics
Hack NY
YC Hacks
M Hacks
Hop Hacks
Cal Hacks
Facebook Hackathon

**Comment by avinash201199** [comment]
> For Computer Science:
> 
> ACM ICPC Yandex.Algorithm VK Cup IEEE Xtreme
> 
> For Data Science and Artificial Intelligence:
> 
> World Computer Chess Championship Angry Birds AI Competition Battle of Bots
> 
> For Cybersecurity:
> 
> Global Cyberlympics NYU Cybersecurity Awareness Week National Collegiate Cyber Defence Competition MITRE Cyber Academy Contests Cyber Fed DARPA Cyber Grand Challenge
> 
> For Robotics:
> 
> DARPA Grand Robotics Challenge VEX Robotics BEST Robotics BotBall GEAR Robotics Competition Int’l Robot Olympiad
> 
> For Mathematics:
> 
> William Lowell Putnam Mathematics Competition International Mathematics Competition for Undergraduates Mathematical Contest in Modelling Interdisciplinary Contest in Modelling Math Jeopardy Contest SIAM Student Paper Competition
> 
> For Physics:
> 
> Rudolf Ortvay Competition in Physics University Physics Competition
> 
> Annual Hackathons and Tech Contests:
> 
> NASA Space Apps Challenge Hack MIT Make MIT Penapps MIT Hacking Medicine University Hacker Olympics Hack NY YC Hacks M Hacks Hop Hacks Cal Hacks Facebook Hackathon

go ahead :)
