### ISSUE TITLE
GitKraken Ambassador Program

### ISSUE THREAD

**Issue by Sidd2024** [avinash201199/Competitions-and-Programs-List#132]
GitKraken Ambassadors are a group of professionals from all around the world who love sharing their knowledge about Git and the GitKraken Git Client. They are passionate about learning and sharing technical expertise by creating articles, videos, and other content.

**Comment by Sidd2024** [comment]
please add the hacktoberfest label to both issues and pr
thank you...

**Comment by avinash201199** [comment]
> please add the hacktoberfest label to both issues and pr thank you...

will add the label in pull request don't worry

**Comment by Sidd2024** [comment]
here, please review and merge #135

**Comment by avinash201199** [comment]
done , thank you for your contribution , follow for more
