### ISSUE TITLE
MLH Prep Program

### ISSUE THREAD

**Issue by Sidd2024** [avinash201199/Competitions-and-Programs-List#136]
The MLH Fellowship Prep Program is a 3-week preparation program for aspiring technologists who are interested in experiencing the fellowship before committing to the full 12 weeks. One will build  portfolio of personal projects & experiment with new technologies by collaborating in small groups through a short hackathon sprint.

**Comment by avinash201199** [comment]
It's already added :)

**Comment by Sidd2024** [comment]
Prep program is different from fellowship. It is short and without stipend, so more chances of selection.

**Comment by Sidd2024** [comment]
Done #137
