### ISSUE TITLE
GitLab Hackathon

### ISSUE THREAD

**Issue by Ujjawal-Kothari** [avinash201199/Competitions-and-Programs-List#155]
The Hackathon is a virtual event open to anyone who is interested in contributing code, documentation, translations, UX designs and more to GitLab. By participating in GitLab's Hackathon, you have the opportunity to work on issues that matter to you and advance your skills/experience while joining a global, diverse and inclusive team of contributors and GitLab team members.
For this Hackathon, we are introducing the following contribution areas: Website, Security, Front-end, Back-end, Documentation. Prizes are awarded to participants for having Merge Requests (MRs) merged that contribute to the issues/epics linked below on each contribution area.

**Comment by ayeolakenny** [comment]
can you assign this to me

**Comment by Ujjawal-Kothari** [comment]
Hey! Raised a PR #181
