### ISSUE TITLE
Visa Code UR Way

### ISSUE THREAD

**Issue by kusumpriya19** [avinash201199/Competitions-and-Programs-List#17]
![image](https://user-images.githubusercontent.com/72653558/135711762-c4d0bbcc-3cb9-4742-b661-c1a8f021c70f.png)
Visa’s internship program is a great way to learn and explore the world of digital payments. During this 10-12-week program, you will be immersed in a team, working on important projects. We benefit from the experience you bring, and you get to work on strategic initiatives, meet brilliant peers, and gain executive exposure. At Visa, we'll help you make your mark as you kick-start your career.

New College Graduate Opportunities

Visa provides a wide range of full-time opportunities for new college graduates across the organization. If you have ambition, focus, and drive, and are interested in joining a global team focused on changing the way the world pays and is paid, we want to talk to you.

Eligibility:

Pre-final & Final year women students only 
Graduating year - 2020 & 2021 
Only from the selected list of engineering colleges in India (check your college)
Study discipline – B.E/B.Tech, M.Tech/Dual Degree 
Study branch – All branches allowed 
Challenge format:

5 Programming questions (Based upon the concepts of Data Structures & Algorithms)

Link - https://assessment.hackerearth.com/challenges/hiring/visa-code-your-way-2019/

**Comment by avinash201199** [comment]
Are you adding ?

**Comment by kusumpriya19** [comment]
Yes , Yes I will add it now !!

**Comment by avinash201199** [comment]
> Yes , Yes I will add it now !!

Great :)

**Comment by kusumpriya19** [comment]
@avinash201199 #52 . hey !! here is the pr
