### ISSUE TITLE
Add competition from readme to script.js file which are not added, so that it can refelect on webiste - comment down to be assigned

### ISSUE THREAD

**Issue by avinash201199** [avinash201199/Competitions-and-Programs-List#228]
![image](https://user-images.githubusercontent.com/61057666/193580914-6ecd0963-7597-4177-99a8-d2248889abd1.png)

**Comment by ashutoshshisodia** [comment]
@avinash201199 Please assign to me

**Comment by avinash201199** [comment]
please add it in alphabetically
