### ISSUE TITLE
Add social media icons in footer - comment down to be assigned

### ISSUE THREAD

**Issue by avinash201199** [avinash201199/Competitions-and-Programs-List#229]
![image](https://user-images.githubusercontent.com/61057666/193588394-eb3b1fdd-a10c-41fb-94f5-82dbcda2755c.png)

Linkedin- https://www.linkedin.com/in/avinash-singh-071b79175/
Github- https://github.com/avinash201199/Competitions-and-Programs-List
email- avinash201199@gmail.com
instagram- https://www.instagram.com/lets__code/

**Comment by saurabh190802** [comment]
@avinash201199 
Its done sir.
just assign me so that i can make a PR.

https://user-images.githubusercontent.com/75023861/193618273-065a6968-6640-4fb0-8678-80c72a60ac8e.mp4

**Comment by avinash201199** [comment]
Thank you :)

**Comment by saurabh190802** [comment]
@avinash201199 
Have created a PR
