### ISSUE TITLE
Adding Microsoft Fix-a-Thon

### ISSUE THREAD

**Issue by saurabh190802** [avinash201199/Competitions-and-Programs-List#236]
@avinash201199 
Sir, Kindly assign me this. So that I can start working on this.

**Comment by avinash201199** [comment]
already added , thank you

**Comment by saurabh190802** [comment]
Its in readme not in scripts. So i got wrong.
Thanks

**Comment by avinash201199** [comment]
you can add those which are not in script , will accept your pr

**Comment by saurabh190802** [comment]
![image](https://user-images.githubusercontent.com/75023861/193656895-07e00f7b-c5e9-468c-a5f6-978bac86afb0.png)

There are total 21 differences so i m trying to add all.

**Comment by avinash201199** [comment]
> ![image](https://user-images.githubusercontent.com/75023861/193656895-07e00f7b-c5e9-468c-a5f6-978bac86afb0.png)
> 
> There are total 21 differences so i m trying to add all.

great

**Comment by saurabh190802** [comment]
mostly everything is added to scripts
#252
