### ISSUE TITLE
Adding snackdown organised by codechef

### ISSUE THREAD

**Issue by Sayam241020** [avinash201199/Competitions-and-Programs-List#250]
SnackDown is India's global programming event that invites coders from all over the world - everyone from middle/high school to colleges to working professionals from the industry, to make an attempt to take home the coveted crown of SnackDown champion.

**Comment by avinash201199** [comment]
https://github.com/avinash201199/Competitions-and-Programs-List/tree/main/Coding%20Contest

add coding contest in this directory
