### ISSUE TITLE
Added "SMART INDIA HACKATHON" by Govt of India 

### ISSUE THREAD

**Issue by Shrey-Nahar** [avinash201199/Competitions-and-Programs-List#271]
adding complete information about "SMART INDIA HACKATHON"

**Comment by Shrey-Nahar** [comment]
@avinash201199  is this already done ??

**Comment by ashutoshshisodia** [comment]
@Shrey-Nahar this is already covered.

**Comment by Shrey-Nahar** [comment]
@ashutoshshisodia i will delete this issue and a new one that is not covered..
