### ISSUE TITLE
Adding Animations to SVGs

### ISSUE THREAD

**Issue by Garvit1809** [avinash201199/Competitions-and-Programs-List#299]
The social icons in the footer are not rendering properly
![image](https://user-images.githubusercontent.com/89806031/194060885-aeadf027-0c7f-4408-bc52-090aa04e3120.png)

Also on HOVER, they get big instantaneously, so I would like to add an animation to it as well to the GitHub Icon on top.

**Comment by Amool-kk** [comment]
@Garvit1809 please assign me this

**Comment by Garvit1809** [comment]
As this task has been done and my pull request had a bug earlier, so I would like to add animations on hover and click on SVG's now.
Also, due to a tag, the top Github SVG is showing some ugly behavior, would fix that too.
