### ISSUE TITLE
ACM ICPC

### ISSUE THREAD

**Issue by Ankurrsingh** [avinash201199/Competitions-and-Programs-List#3]
ACM ICPC(Association for Computing Machinery – International Collegiate Programming Contest) is a worldwide annual multi-tiered programming contest being organized for over thirteen years.
It is the largest student programming contest in the world! Globally, this competition is considered the most prestigious and includes elite young programmers.

**Comment by avinash201199** [comment]
@Ankurrsingh already added , choose another
