### ISSUE TITLE
ACM ICPC ( Association of Computing Machinery International Collegiate Programming Contest )

### ISSUE THREAD

**Issue by illusion001** [avinash201199/Competitions-and-Programs-List#30]
The International Collegiate Programming Contest is an algorithmic programming contest for college students. Teams of three, representing their university, work to solve the most real-world problems, fostering collaboration, creativity, innovation, and the ability to perform under pressure. Through training and competition, teams challenge each other to raise the bar on the possible. Quite simply, it is the oldest, largest, and most prestigious programming contest in the world.

**Comment by avinash201199** [comment]
Already added
