### ISSUE TITLE
I want to add Job-a-Thon by gfg

### ISSUE THREAD

**Issue by deep2002deepika** [avinash201199/Competitions-and-Programs-List#311]
Hello Sir,
I'm Deepika Kumari with Github id-deep2002deepika
I want to contribute to your repository by adding Job-a-Thon by gfg.
Kindly,consider my contribution.I'll be very thankful to you for this oppurtunity.

Regards 
Deepika Kumari

**Comment by avinash201199** [comment]
you can add it in coding contest folder
