### ISSUE TITLE
Hackathon - Bug Bash

### ISSUE THREAD

**Issue by pragyamittal0** [avinash201199/Competitions-and-Programs-List#387]
https://unstop.com/hackathon/bug-bash-technovate-2022-international-institute-of-information-technology-iiit-naya-raipur-439868

Please assign me the task!

**Comment by avinash201199** [comment]
add it in hackathon folder

**Comment by avinash201199** [comment]
if you have made 2 pr in this repo then it's enough ,contribute in other repo

**Comment by pragyamittal0** [comment]
Ni I haven't made 2 pr yet :)
