### ISSUE TITLE
D. E. Shaw Mentorship Program 

### ISSUE THREAD

**Issue by RakshaFauzdar** [avinash201199/Competitions-and-Programs-List#40]
From 2020, D. E. Shaw India introduced DESIS Ascend—a diversity, equity, and
inclusion initiative—to cultivate an environment of continuous learning and
development that enables exceptional people to do their best work.

link : https://www.deshawindia.com/desis-ascend-educare/about.pdf

**Comment by avinash201199** [comment]
Go ahead :)
