### ISSUE TITLE
Want to add Shell Ideas360 competition

### ISSUE THREAD

**Issue by Khushi-Shukla** [avinash201199/Competitions-and-Programs-List#410]

**Comment by avinash201199** [comment]
please tell me more about it

**Comment by Khushi-Shukla** [comment]
It is a global competition organized by Shell International Limited. Both undergrads and postgrads can participate in this contest. Participants submit thier innovative ideas for tackling energy, water and food issues either in teams or individually. After this a project on the idea is to be submitted. Shell mentors and experts also guide in the development.
