### ISSUE TITLE
Update Competition Name: `Script Winter of Code` 

### ISSUE THREAD

**Issue by ShatilKhan** [avinash201199/Competitions-and-Programs-List#475]
Starting 2023 `Script Winter of Code` has been renamed to `Social Winter of Code`
This needs to be changed in the readme.
I am willing to make a PR.
Consider assigning this issue to me.

**Comment by ShatilKhan** [comment]
Done with PR

**Comment by ShatilKhan** [comment]
Part of my CollabCode Carnival contribution
Please add proper labels

**Comment by Shu12388y** [comment]
@ShatilKhan I have not assigned this issue to you. And you have created a PR also.

**Comment by Shu12388y** [comment]
@ShatilKhan This is not a proper way to contribute

**Comment by ShatilKhan** [comment]
Oh so sorry, I wasn’t aware of that rule
I'll keep in mind from next time for sure!
Can I get a pass this time? 
 it was unintentional
