### ISSUE TITLE
NAVBAR IS NOT RESPOSNIVE ON MOBILE DEVICE AND WANT TO ADD SOME FEATURES TO SEARCH BOX 

### ISSUE THREAD

**Issue by Ayusht777** [avinash201199/Competitions-and-Programs-List#477]
![image](https://github.com/avinash201199/Competitions-and-Programs-List/assets/106388215/4cb83ee8-4f37-431d-888e-733744e759b2)

your navbar is not responsive for mobile devices and i wan to add clear input button in search box  also some UI fixes
assigned this issue to me  under  OSEN

**Comment by Ayusht777** [comment]
@0PrashantYadav0  are a contributor

**Comment by Shu12388y** [comment]
@Ayusht777 start working on the issue
