### ISSUE TITLE
Adding Dark Theme to the website

### ISSUE THREAD

**Issue by thanmaisai** [avinash201199/Competitions-and-Programs-List#478]
Dark Theme to the Website

<img width="1439" alt="Screenshot 2023-10-25 at 12 32 52 AM" src="https://github.com/avinash201199/Competitions-and-Programs-List/assets/91474486/9f594513-f53b-4558-b922-105eabc1d5fb">

**Comment by thanmaisai** [comment]
Please assign me this issue, and do add the labels for the issue/PR raised in order to make it a valuable contribution for  OSEN open source program.

**Comment by Shu12388y** [comment]
@thanmaisai start working
