### ISSUE TITLE
Remove outdated competition

### ISSUE THREAD

**Issue by dalvishruti14** [avinash201199/Competitions-and-Programs-List#488]
Walmart Sparkplug 2022 event is outdated and their official website page is not found. 
Thus, the event can be removed from the website.
Can I work on this?
![walmart1](https://github.com/avinash201199/Competitions-and-Programs-List/assets/120911455/9f80f969-cd4f-45ab-b8fd-19939352deca)

**Comment by Shu12388y** [comment]
@dalvishruti14 start working
