### ISSUE TITLE
Adobe India Women-in-Technology Scholarship

### ISSUE THREAD

**Issue by shivi0** [avinash201199/Competitions-and-Programs-List#63]
Through the Adobe India Women-in-Technology Scholarship, Adobe is striving towards creating gender equality in science, technology and engineering domains by encouraging women to showcase their excellence in computing and technology and become future leaders and role models in the field.

Official  Website: https://research.adobe.com/adobe-india-women-in-technology-scholarship/

**Comment by avinash201199** [comment]
go ahead :)
