### ISSUE TITLE
JP Morgan Code for Good

### ISSUE THREAD

**Issue by KuraPriyanka** [avinash201199/Competitions-and-Programs-List#81]
About
JP Morgan Code for Good is a platform for university students, industry experts, and NPOs, where all come together to use technology to build a product that can help in solving real-world problems, not the bigger ones, but putting up a foundation stone for the greater good. Students get to learn from industry experts, and vice-versa. In the end, competent students are offered internships and FTE opportunities with the firm. Students who are studying second year and third year in Computer and related fields are eligible.

Official Website:
https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210072211/ 

Explanation on Video:
https://www.youtube.com/watch?v=UjIU6iwLhAw&t=67s

**Comment by avinash201199** [comment]
> Please assign this issue to me

go ahead :)
