### ISSUE TITLE
Intuit Augment 

### ISSUE THREAD

**Issue by KuraPriyanka** [avinash201199/Competitions-and-Programs-List#89]
About
Intuit is inviting young women technologists to be part of a mentorship program. This is in line with our commitment to power prosperity amongst young engineers to be industry-ready with guidance from domain experts. The mentorship program is specifically designed to equip budding women engineers to develop core competencies and compliment their career aspirations.
Women who are studying 2nd-year B.Tech/B.E  and 3rd-year Dual Degree in Computer Science / Information Technology /Maths & Computing and having cgpa 7 or above. Registration happens in January.

Official Website:
https://www.surveymonkey.com/r/INTUIT_2020

**Comment by avinash201199** [comment]
> Please assign this issue to me.

hey try to contribute on my other repo's too , having so many pr on same repo is not good for considering in hacktoberfest , they verify every pr
